meta_data:
  exp_name: "mad_swap"
  script_path: "run_scripts/train.py"
  num_workers: 2
  job_name: "{dataset}/h_{horizon}-{model}-r_{returns_scale}-guidew_{condition_guidance_w}-ctde_{decentralized_execution}"

variables:
  seed: [100, 200, 300, 400, 500]

  horizon: [24]
  returns_scale: [700]
  dataset: ["swap"]

constants:
  # misc
  seed: 100
  env_type: "swap"
  n_agents: 2
  use_action: True
  discrete_action: False
  residual_attn: True
  decentralized_execution: True
  use_zero_padding: False
  pred_future_padding: True
  use_ddim_sample: False
  n_ddim_steps: 15

  # model
  model: "models.SharedConvAttentionDeconv"
  diffusion: "models.GaussianDiffusion"
  share_inv: False
  history_horizon: 0
  n_diffusion_steps: 100
  action_weight: 10
  loss_weights: null
  loss_discount: 1
  dim_mults: [1, 4, 8]
  returns_condition: True
  predict_epsilon: True
  calc_energy: False
  dim: 256
  hidden_dim: 256
  condition_dropout: 0.25
  condition_guidance_w: 1.2
  train_only_inv: False
  clip_denoised: True
  test_ret: 0.9
  renderer: "utils.MPERenderer"

  # dataset
  loader: "datasets.SequenceDataset"
  # normalizer: "CDFNormalizer"
  normalizer: "LimitsNormalizer"
  max_n_episodes: 100000
  preprocess_fns: []
  use_padding: True
  discount: 0.99
  max_path_length: 25
  termination_penalty: 0.0
  returns_scale: 200.0  # Determined using rewards from the dataset

  # training
  n_steps_per_epoch: 1000000
  n_train_steps: 1000000
  batch_size: 64
  learning_rate: 0.0002
  gradient_accumulate_every: 2
  ema_decay: 0.995
  log_freq: 1000
  save_freq: 50000
  sample_freq: 10000
  n_saves: 5
  save_parallel: False
  n_reference: 3
  save_checkpoints: True

  # eval
  evaluator: "utils.MADEvaluator"
  num_eval: 10
  eval_freq: 100000

  # load checkpoint
  continue_training: True
